[platformio]
default_envs = thermal_mcu

[env:thermal_mcu]
platform = https://github.com/pioarduino/platform-espressif32.git
framework = espidf
board = arduino_nano_esp32
monitor_speed = 115200
upload_speed = 115200
upload_protocol = esptool
